#!/usr/bin/env bash
# Claude Code PreToolUse hook: ensure every `git commit` Claude runs carries
# a DCO sign-off (-s / --signoff). The trailer must be produced by the flag --
# project policy is to never write `Signed-off-by:` lines manually.
#
# Claude Code delivers tool input as a JSON payload on stdin
# (https://docs.claude.com/claude-code/hooks). Falls back to the legacy
# CLAUDE_TOOL_INPUT_command env var so the hook still functions in harnesses
# that pre-resolved tool input that way. Bare manual invocation (no stdin,
# no env var) is treated as "no command to inspect" and allowed.

set -euo pipefail

CMD="${CLAUDE_TOOL_INPUT_command:-}"

if [ -z "$CMD" ] && [ ! -t 0 ]; then
  PAYLOAD=$(cat || true)
  if [ -n "$PAYLOAD" ] && command -v jq >/dev/null 2>&1; then
    CMD=$(printf '%s' "$PAYLOAD" | jq -r '.tool_input.command // empty' 2>/dev/null || true)
  fi
fi

if [ -z "$CMD" ]; then
  exit 0
fi

# Strip single- and double-quoted segments so `-s` inside a message string
# (false-positive) and `git commit` inside a quoted echo (false-negative both
# ways) are removed before pattern matching. Nested quoting is out of scope --
# the project's actual commit commands don't use it.
STRIPPED=$(printf '%s' "$CMD" | sed "s/\"[^\"]*\"//g; s/'[^']*'//g")

# Only fire when `git commit` appears as a distinct subcommand. Excludes
# `git commit-tree`, `git commit-graph`, and any occurrence inside a quoted
# string that was already stripped above. Boundary on whitespace or EOL.
if ! printf '%s' "$STRIPPED" | grep -qE '(^|[;&|][[:space:]]*)git[[:space:]]+commit([[:space:]]|$)'; then
  exit 0
fi

# Accept `-s` or `--signoff`, including combined short flags like `-sS`,
# `-sm`, `-sam`, `-Ss`. The project's documented best practice is `git
# commit -sS -m "..."` (DCO + GPG together), so the combined form must
# not be rejected.
if printf '%s' "$STRIPPED" | grep -qE -- '(^|[[:space:]])-[A-Za-z]*s[A-Za-z]*([[:space:]]|$)|(^|[[:space:]])--signoff([[:space:]]|=|$)'; then
  exit 0
fi

cat >&2 <<'EOF'
BLOCK: git commit is missing DCO sign-off.

This project requires every commit to carry a `Signed-off-by:` trailer,
generated by passing the `-s` (or `--signoff`) flag to `git commit`. The
trailer must not be written manually -- only `-s` produces a valid one
from `user.name` and `user.email` in git config.

Fix:
  git commit -s ...                       # new commit
  git commit --amend --no-edit -s         # fix the most-recent commit

Combined short flags are accepted: -sS (DCO + GPG sign), -sm, -sam, etc.
See AGENTS.md "Git Workflow Custom" for the canonical policy.
EOF
exit 2
