validate = true
number = true
wrap = "no"
end_of_line = "lf"
extensions = [
    "gfm",
    "footnote",
    "front_matters",
    "simple_breaks",
    "wikilink",
    "gfm_alerts",
    "toc",
]

[plugin.mkdocs]
align_semantic_breaks_in_lists = true
ignore_missing_references      = true
