name: release-plz

on:
    push:
        branches: [main]

jobs:
    release-plz-release:
        name: Release-plz release
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  fetch-depth: 0
                  # persist-credentials required for pushing signed tags via git CLI
                  persist-credentials: true
            - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
              with:
                  install: true
                  cache_key: "mise-v1-{{platform}}-{{install_args_hash}}-{{file_hash}}"
                  cache: true
            - name: Run release-plz
              uses: release-plz/action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5.131
              with:
                  command: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release-plz-pr:
        name: Release-plz PR
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            contents: write
            pull-requests: write
        concurrency:
            group: release-plz-${{ github.ref }}
            cancel-in-progress: false
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
              with:
                  install: true
                  cache_key: "mise-v1-{{platform}}-{{install_args_hash}}-{{file_hash}}"
                  cache: true
            - name: Run release-plz
              uses: release-plz/action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5.131
              with:
                  command: release-pr
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
